server:
  port: 8089

spring:
  application:
    name: letters
  datasource:
    url: jdbc:postgresql://localhost:5433/letter_request
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 2KB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
